In [4]:
import pandas
import numpy

In [121]:
#Load the data
df = pandas.read_csv('pokedex.csv')
df

,#,Name,Type 1,Type 2,HP,Atk,Def,SP Atk,SP Def,Spd,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,525
3,3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,309
...,...,...,...,...,...,...,...,...,...,...,...
1040,896,Glastrier,Ice,NaN,100,145,130,65,110,30,580
1041,897,Spectrier,Ghost,NaN,100,65,60,145,80,130,580
1042,898,Calyrex,Psychic,Grass,100,80,80,80,80,80,500
1043,898,Ice Rider,Psychic,Ice,100,165,150,85,130,50,680
1044,898,Shadow Rider,Psychic,Ghost,100,85,80,165,100,150,680

In [43]:
#Read Headers
df.columns
#Read each Column
df[['#','Name' ]]
#Read each Row
df.head(4)

for index, row in df.iterrows():
    print(index, row['HP'])
#Read a specific location (R,C)
df.iloc[40]
df.iloc[99:103]

0 45
1 60
2 80
3 80
4 39
5 58
6 78
7 78
8 78
9 44
10 59
11 79
12 79
13 45
14 50
15 60
16 40
17 45
18 65
19 65
20 40
21 63
22 83
23 83
24 30
25 30
26 55
27 75
28 40
29 65
30 35
31 60
32 35
33 45
34 60
35 60
36 50
37 50
38 75
39 75
40 55
41 70
42 90
43 46
44 61
45 81
46 70
47 95
48 38
49 38
50 73
51 73
52 115
53 140
54 40
55 75
56 45
57 60
58 75
59 35
60 60
61 60
62 70
63 10
64 10
65 35
66 35
67 40
68 40
69 50
70 65
71 65
72 50
73 80
74 40
75 65
76 55
77 90
78 40
79 65
80 90
81 25
82 40
83 55
84 55
85 70
86 80
87 90
88 50
89 65
90 80
91 40
92 80
93 40
94 40
95 55
96 55
97 80
98 80
99 50
100 50
101 65
102 65
103 90
104 90
105 95
106 95
107 95
108 25
109 50
110 52
111 52
112 35
113 60
114 65
115 90
116 80
117 80
118 105
119 105
120 30
121 50
122 30
123 45
124 60
125 60
126 35
127 60
128 85
129 30
130 55
131 40
132 60
133 60
134 95
135 95
136 50
137 60
138 60
139 50
140 50
141 90
142 40
143 65
144 65
145 80
146 105
147 250
148 65
149 105
150 105
151 30
152 55
153 45
154 80
155 30
156 60
157 40
158 50
159 70
160 65
161 65
162 65
163 65
164 65
165 75
166 20
167 95
168 95
169 130
170 48
171 55
172 65
173 130
174 65
175 65
176 65
177 35
178 70
179 30
180 60
181 80
182 80
183 160
184 90
185 90
186 90
187 90
188 90
189 90
190 41
191 61
192 91
193 106
194 106
195 106
196 100
197 45
198 60
199 80
200 39
201 58
202 78
203 50
204 65
205 85
206 35
207 85
208 60
209 100
210 40
211 55
212 40
213 70
214 85
215 75
216 125
217 20
218 50
219 90
220 35
221 55
222 40
223 65
224 55
225 70
226 90
227 90
228 75
229 70
230 100
231 70
232 90
233 35
234 55
235 75
236 55
237 30
238 75
239 65
240 55
241 95
242 65
243 95
244 60
245 95
246 95
247 60
248 48
249 190
250 70
251 50
252 75
253 100
254 65
255 75
256 75
257 60
258 90
259 65
260 70
261 70
262 20
263 80
264 80
265 55
266 60
267 90
268 40
269 60
270 50
271 100
272 65
273 60
274 35
275 75
276 45
277 85
278 65
279 45
280 75
281 75
282 75
283 90
284 90
285 85
286 73
287 55
288 35
289 50
290 45
291 45
292 45
293 95
294 255
295 90
296 115
297 100
298 50
299 70
300 100
301 100
302 106
303 106
304 100
305 40
306 50
307 70
308 70
309 45
310 60
311 80
312 80
313 50
314 70
315 100
316 100
317 35
318 70
319 38
320 38
321 78
322 78
323 45
324 50
325 60
326 50
327 60
328 40
329 60
330 80
331 40
332 70
333 90
334 40
335 60
336 40
337 60
338 28
339 38
340 68
341 68
342 40
343 70
344 60
345 60
346 60
347 80
348 150
349 31
350 61
351 1
352 64
353 84
354 104
355 72
356 144
357 50
358 30
359 50
360 70
361 50
362 50
363 50
364 50
365 50
366 60
367 70
368 70
369 30
370 60
371 60
372 40
373 70
374 70
375 60
376 60
377 65
378 65
379 50
380 70
381 100
382 45
383 70
384 70
385 130
386 170
387 60
388 70
389 70
390 70
391 60
392 80
393 60
394 45
395 50
396 80
397 50
398 70
399 45
400 75
401 75
402 73
403 73
404 90
405 90
406 50
407 110
408 43
409 63
410 40
411 60
412 66
413 86
414 45
415 75
416 20
417 95
418 70
419 70
420 70
421 70
422 60
423 44
424 64
425 64
426 20
427 40
428 99
429 75
430 65
431 65
432 95
433 50
434 80
435 80
436 70
437 90
438 110
439 35
440 55
441 55
442 100
443 43
444 45
445 65
446 95
447 95
448 40
449 60
450 80
451 80
452 80
453 80
454 80
455 80
456 80
457 80
458 80
459 100
460 100
461 100
462 100
463 105
464 105
465 100
466 50
467 50
468 50
469 50
470 55
471 75
472 95
473 44
474 64
475 76
476 53
477 64
478 84
479 40
480 55
481 85
482 59
483 79
484 37
485 77
486 45
487 60
488 80
489 40
490 60
491 67
492 97
493 30
494 60
495 40
496 60
497 60
498 60
499 70
500 30
501 70
502 60
503 55
504 85
505 45
506 70
507 76
508 111
509 75
510 90
511 150
512 55
513 65
514 65
515 60
516 100
517 49
518 71
519 45
520 63
521 103
522 57
523 67
524 50
525 20
526 100
527 76
528 50
529 58
530 68
531 108
532 108
533 135
534 40
535 70
536 70
537 68
538 108
539 40
540 70
541 48
542 83
543 74
544 49
545 69
546 45
547 60
548 90
549 90
550 70
551 70
552 110
553 115
554 100
555 75
556 75
557 85
558 86
559 65
560 65
561 75
562 110
563 85
564 68
565 68
566 60
567 45
568 70
569 50
570 50
571 50
572 50
573 50
574 50
575 75
576 80
577 75
578 100
579 90
580 91
581 110
582 150
583 150
584 120
585 80
586 100
587 70
588 100
589 100
590 120
591 100
592 45
593 60
594 75
595 65
596 90
597 110
598 55
599 75
600 95
601 45
602 60
603 45
604 65
605 85
606 41
607 64
608 50
609 75
610 50
611 75
612 50
613 75
614 76
615 116
616 50
617 62
618 80
619 45
620 75
621 55
622 70
623 85
624 65
625 67
626 60
627 110
628 103
629 103
630 75
631 85
632 105
633 50
634 75
635 105
636 120
637 75
638 45
639 55
640 75
641 30
642 40
643 60
644 40
645 60
646 45
647 70
648 70
649 70
650 50
651 60
652 95
653 70
654 70
655 105
656 105
657 105
658 105
659 75
660 50
661 70
662 50
663 65
664 72
665 38
666 38
667 58
668 54
669 74
670 55
671 75
672 50
673 80
674 40
675 60
676 55
677 75
678 45
679 60
680 70
681 45
682 65
683 110
684 62
685 75
686 36
687 51
688 71
689 60
690 80
691 55
692 50
693 70
694 69
695 114
696 55
697 100
698 165
699 50
700 70
701 44
702 74
703 40
704 60
705 60
706 35
707 65
708 85
709 55
710 75
711 50
712 60
713 60
714 46
715 66
716 76
717 55
718 95
719 80
720 50
721 80
722 109
723 109
724 45
725 65
726 77
727 59
728 89
729 45
730 65
731 95
732 70
733 100
734 70
735 110
736 85
737 58
738 52
739 72
740 92
741 55
742 85
743 91
744 91
745 91
746 79
747 79
748 79
749 79
750 100
751 100
752 89
753 89
754 125
755 125
756 125
757 91
758 91
759 100
760 100
761 71
762 56
763 61
764 88
765 40
766 59
767 75
768 41
769 54
770 72
771 72
772 38
773 85
774 45
775 62
776 78
777 38
778 45
779 80
780 62
781 86
782 44
783 54
784 78
785 66
786 123
787 67
788 95
789 75
790 62
791 74
792 74
793 45
794 59
795 60
796 60
797 78
798 101
799 62
800 82
801 53
802 86
803 42
804 72
805 50
806 65
807 50
808 71
809 44
810 62
811 58
812 82
813 77
814 123
815 95
816 78
817 67
818 50
819 45
820 68
821 90
822 57
823 43
824 85
825 49
826 44
827 54
828 59
829 65
830 55
831 75
832 85
833 55
834 95
835 40
836 85
837 126
838 126
839 108
840 54
841 216
842 50
843 50
844 80
845 80
846 80
847 68
848 78
849 78
850 45
851 65
852 95
853 50
854 60
855 80
856 35
857 55
858 80
859 48
860 88
861 47
862 57
863 77
864 47
865 97
866 75
867 75
868 75
869 75
870 40
871 60
872 45
873 45
874 75
875 85
876 75
877 45
878 45
879 50
880 50
881 70
882 100
883 38
884 68
885 40
886 70
887 40
888 60
889 48
890 68
891 70
892 120
893 42
894 52
895 72
896 51
897 90
898 100
899 25
900 75
901 55
902 85
903 55
904 95
905 95
906 60
907 60
908 65
909 60
910 65
911 55
912 68
913 78
914 70
915 45
916 55
917 75
918 70
919 70
920 70
921 70
922 43
923 43
924 137
925 137
926 109
927 107
928 71
929 83
930 97
931 59
932 223
933 97
934 97
935 97
936 97
937 80
938 90
939 67
940 73
941 61
942 53
943 88
944 46
945 135
946 50
947 70
948 100
949 50
950 65
951 80
952 50
953 65
954 70
955 70
956 120
957 38
958 68
959 98
960 25
961 50
962 60
963 40
964 70
965 40
966 60
967 42
968 72
969 50
970 90
971 59
972 69
973 30
974 80
975 110
976 40
977 70
978 110
979 52
980 72
981 70
982 41
983 61
984 40
985 75
986 75
987 50
988 100
989 50
990 80
991 40
992 60
993 42
994 57
995 57
996 45
997 65
998 95
999 93
1000 70
1001 60
1002 62
1003 80
1004 58
1005 45
1006 65
1007 65
1008 48
1009 30
1010 70
1011 100
1012 75
1013 75
1014 60
1015 70
1016 58
1017 58
1018 72
1019 122
1020 90
1021 90
1022 90
1023 90
1024 70
1025 28
1026 68
1027 88
1028 92
1029 92
1030 92
1031 92
1032 140
1033 255
1034 60
1035 100
1036 100
1037 105
1038 80
1039 200
1040 100
1041 100
1042 100
1043 100
1044 100

,#,Name,Type 1,Type 2,HP,Atk,Def,SP Atk,SP Def,Spd,Total
99,77,Ponyta,Fire,NaN,50,85,55,65,65,90,410
100,77,Galarian Ponyta,Psychic,NaN,50,85,55,65,65,90,410
101,78,Rapidash,Fire,NaN,65,100,70,80,80,105,500
102,78,Galarian Rapidash,Psychic,Fairy,65,100,70,80,80,105,500

In [64]:
#sorting/describing data
#df.loc[df['Type'] == "Fire"]
df.describe()
df.sort_values(['Type 1', 'Name'], ascending = True)

       #       Name Type 1  Type 2   HP  Atk  Def  SP Atk  SP Def  Spd  Total
721  617   Accelgor    Bug     NaN   80   70   40     100      60  145    495
213  168    Ariados    Bug  Poison   70   90   70      60      70   40    400
325  267  Beautifly    Bug  Flying   60   70   50     100      50   65    395
18    15   Beedrill    Bug  Poison   65   90   40      45      80   75    395
960  824    Blipbug    Bug     NaN   25   20   20      25      45   45    180
..   ...        ...    ...     ...  ...  ...  ...     ...     ...  ...    ...
386  321    Wailord  Water     NaN  170   90   45      90      45   60    500
10     8  Wartortle  Water     NaN   59   63   80      65      80   58    405
407  340   Whiscash  Water  Ground  110   78   73      76      71   60    468
336  278    Wingull  Water  Flying   40   30   30      55      30   85    270
240  194     Wooper  Water  Ground   55   45   45      25      25   15    210

[1045 rows x 11 columns]

In [122]:
#Making changes to data (New Columns)
df['Count'] = 1
#Rearranging Columns
cols = list(df.columns.values)
df = df [cols[0:4] + [cols[-1]] + cols[5:10]]
df

In [91]:
#Saving data
df.to_csv('StudyPokedex.csv')
df.to_excel('ExcelPokedex.xlsx', index = False)
df.to_csv('TxtPokedex', index = False, sep = '\t')

In [109]:
#Filtering Data
df.loc[(df['Type 1'] == 'Poison') & (df['Type 2'] == 'Dark')]
df.loc[(df['Type 1'] == 'Poison') | (df['Type 1'] == 'Dark') & (df['SP Atk'] > 100)]
new_df = df.loc[(df['Type 1'] == 'Poison') | (df['Type 1'] == 'Dark') & (df['SP Atk'] > 100)]
#for new index, use reset_index, and for dropping old index use drop = True, and for self reset use inplce = True
new_df.reset_index(drop = True, inplace = True)
new_df
#Regex Filtering re stands for regular expressions
import re

df.loc[df['Name'].str.contains('Mega')]
#note (~ if for not in pandas)
df.loc[~df['Name'].str.contains('Mega')]

df.loc[df['Type 1'].str.contains('fire|grass',flags = re.I,regex = True)]
df.loc[df['Name'].str.contains('bu[a-z]*',flags = re.I,regex = True)]
df.loc[df['Name'].str.contains('^bu[a-z]*',flags = re.I,regex = True)]

,#,Name,Type 1,Type 2,HP,Atk,Def,SP Atk,SP Def,Spd,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,318
15,12,Butterfree,Bug,Flying,60,45,50,90,80,70,395
489,406,Budew,Grass,Poison,40,30,35,50,70,55,280
495,412,Burmy,Bug,NaN,40,29,45,29,45,36,224
503,418,Buizel,Water,NaN,55,65,35,60,30,85,330
512,427,Buneary,Normal,NaN,55,66,44,44,56,85,350
772,659,Bunnelby,Normal,NaN,38,36,38,32,36,57,237
927,794,Buzzwole,Bug,Fighting,107,139,139,53,53,79,570

In [115]:
#Conditional Changes
df.loc[df['Type 1'] == 'Grass', 'Name'] = 'Graminha'
df

,#,Name,Type 1,Type 2,HP,Atk,Def,SP Atk,SP Def,Spd,Total
0,1,Gramoso,Grass,Poison,45,49,49,65,65,45,318
1,2,Gramoso,Grass,Poison,60,62,63,80,80,60,405
2,3,Gramoso,Grass,Poison,80,82,83,100,100,80,525
3,3,Gramoso,Grass,Poison,80,100,123,122,120,80,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,309
...,...,...,...,...,...,...,...,...,...,...,...
1040,896,Glastrier,Ice,NaN,100,145,130,65,110,30,580
1041,897,Spectrier,Ghost,NaN,100,65,60,145,80,130,580
1042,898,Calyrex,Psychic,Grass,100,80,80,80,80,80,500
1043,898,Ice Rider,Psychic,Ice,100,165,150,85,130,50,680
1044,898,Shadow Rider,Psychic,Ghost,100,85,80,165,100,150,680

In [124]:
#Aggregate Statistics (Groupby)
df.groupby(['Type 1']).mean()
df.groupby(['Type 1']).mean().sort_values('Spd', ascending = False)
df.groupby(['Type 1']).sum()
df.groupby(['Type 1']).count()['Count']
df.groupby(['Type 1', 'Type 2']).count()['Count']

Type 1  Type 2
Bug     Electric     4
        Fairy        2
        Fighting     4
        Fire         2
        Flying      14
                    ..
Water   Ice          4
        Poison       3
        Psychic      6
        Rock         5
        Steel        1
Name: Count, Length: 174, dtype: int64

In [130]:
#Big Data
new_df = pd.DataFrame
#for df in pd.read_csv('pokedex.csv', chunksize = 140):
    #print('--------------------------------------------------')
    #print(df)
for df in pd.read_csv('pokedex.csv', chunksize = 140):
    chunk = df.df.groupby(['Type 1']).count()
    new_df = pd.concat

AttributeError: 'DataFrame' object has no attribute 'df'